### ISSUE TITLE
Is IE really the old Natural Ventilation whole house positive ventilation from loft?

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#177]
I am playing with MHEP for a bit and have realized that the _Ventilation looses_ are Zero when we choose '_Intermittent extract ventilation (IE)_' as ventilation system. This is because for the old _Natural Ventilation whole house positive ventilation from loft_ there are only infiltration looses and no ventilation looses.

Should it be more accurate to make the IE be as the old _'Whole house extract ventilation or positive input ventilation from outside"_ in which case  ventilation looses are  are **0.5 x air change rate**??

**Comment by marianneURBED** [comment]
No, that's right. SAP just assigns the 10 m3/hr rate to each fan and leaves it at that. Considering they're not running most of the time, that might not be too wide of the mark. So it's really just counting the fact that there's a hole in the wall, rather than accounting for the air pulled through by the fan. 

Does feel odd though - and could give a false picture if it makes intermittent extract look like it's better performing than other ventilation methods. 

Might not be something we tackle now, but I guess ultimately being able to show the losses associated with the extract fans separately from the infiltration rate would be good.

**Comment by marianneURBED** [comment]
Right. From what I've read we should leave it as it is. 10m3/hr for intermittent fans is an assumed average - accounting for when the fan is running and when it isn't (most of the time). 

'Whole house extract ventilation' only applies to continuously running systems  - whether centralised or decentralised. 

This being the case, think it's more of a representation problem with the house diagram - which could give a false picture if it means people think there are no losses associated with intermittent extract - rather than a calculation problem. 

So maybe this is something we look at when we look at the report - would it be possible to separate out the 10m3/hr for intermittent extracts, and passive vents, and add it to the 'ventilation' arrow, rather than the infiltration arrow? (This all comes from a bad confusion between ventilation and infiltration, that the UK construction industry seems to suffer from).

**Comment by cagabi** [comment]
I have made the changes so that looses due to Extract Ventilation Points are now considered Ventilation looses instead of Infiltration looses. I have added notes in the code to make clear we are doing calculations different than SAP. Also for the assessor I have divided the _Ventilation and  Infiltration_ page in two clear different sections to avoid the confusion you mention
