### ISSUE TITLE
Comfort Survey Responses not pulling through to report. 

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#210]
The responses from housholders on their perceptions of comfort from the questionnaire don't seem to be pulling through to the report. Section 1.8, Figure 13 - relevant boxes should be highlighted and go red or green depending on response.

**Comment by cagabi** [comment]
Ok, done, the problem was not easy to find, it had to do with the printer configuration that by default (in order to save ink) when printing a website, backgrounds colors are not printed.

To avoid assessors not realizing to allow printing background, now the green and red boxed are pictures not backgrounds so will always be printed.
