### ISSUE TITLE
I don't think this sentence is very clear

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#217]

**Comment by gervasemangwana** [comment]
If your home is uncomfortably cold or you have problems with condensation and damp, the most important thing you can do is reduce space heating demand by improving the efficiency of your building fabric. This will also improve the comfort and health of your home. 

It is true in a way but doesn't really say why or how.

**Comment by marianneURBED** [comment]
Amended to: 
If your home is uncomfortably cold or you have problems with condensation and damp, the most important thing you can do is improve the efficiency of its fabric, so that it stays warmer for longer. This will also improve the comfort and health of your home. The lower the number given for 'Space Heating Demand', the more efficient your home is, the easier it will be to keep it warm, making you more comfortable and reducing the risk of condensation and damp. 

This text included in the PDF at #211 so closing this issue for now.
