### ISSUE TITLE
Sentence about renewables for Figure 7 still not 100% clear or accurate

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#218]
Propose instead:

Where renewable technologies are present or proposed the stack has been displaced by the amount of primary energy they save. So the level of the graph shows your net primary energy once renewables have been accounted for.

**Comment by marianneURBED** [comment]
I think that's just about right: 
"Where renewable technologies are present or proposed the stack has been displaced by the amount of primary energy they save. So the level of the graph shows your net primary energy once renewables have been accounted for, against the Carbon Coop target."

Have updated the text in PDF at #211 to reflect this, so closing the issue here for now.
