### ISSUE TITLE
Need to add units to performance targets

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#222]
Need to think about how to do this for all measures without someone losing the will to live

**Comment by marianneURBED** [comment]
Agree. Carlos - you said yesterday that there should be a way of doing this relatively simply. If this turns out to not be true let us know. 
Given it's a report formatting issue, I've added this to the PDF at issue #211. Leaving open here though as I realise it's about more than just updating a bit of text etc in the report.

**Comment by cagabi** [comment]
Hi,

I have added the units to all the fabric elements in the library but i cannot add them to the measures already applied to an assessment, so for assesment already done, they have to live without units

Also none of the Storage Type, Pipework insulation and Space Heating Controls items in the library have a performance target

**Comment by marianneURBED** [comment]
That's great. The Storage Type, Pipework Insulation and Space Heating Controls realistically don't have a sensible performance target unit (I think) - but we can always wangle this later if needed. 

Can probably close this issue now?

**Comment by cagabi** [comment]
Thanks, yes I'm closing this issue now
