### ISSUE TITLE
Fans and Pumps consumption very large for DEV and MVHR

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#225]
Adding over 1000 kWh per annum to electricity consumption

**Comment by marianneURBED** [comment]
Agree these are high. Think it is to do with some of the default very conservative assumptions made in SAP. I'll need to do a bit more research on these to check it out and if necessary, we can deviate from these assumptions.

**Comment by marianneURBED** [comment]
So I've looked at this. Turns out the defaults in SAP for Specific Fan Power are just really high, and then when you look at the Appendix Q reported figures for various systems they are up to 90% less than the defaults. 

I've updated the figures in the g-sheet for where systems are measures to reflect this - highlighted in blue on the g-sheet in the ventilations page. I've left the defaults in place for where the system is one that is not a measure (i.e. is already in place in a house). Reason for this is I understand that SFP has improved markedly over the last few years, and also if we're giving a target/ understanding 

Carlos - are you ok to update this in the tool? Thanks!

**Comment by gervasemangwana** [comment]
Great. Thanks for looking at this. 

G

**Comment by cagabi** [comment]
Yes, easy. Again I'll do it tomorrw with the other library stuff

**Comment by marianneURBED** [comment]
For reference, good discussion on how SAP treats MVHR. Basically assumes that all installs will be crap (thereby not creating much of an incentive to make them better): http://www.greenbuildingforum.co.uk/newforum/comments.php?DiscussionID=3017

**Comment by gervasemangwana** [comment]
Wow. Thanks. Very interesting.

Must get round to fitting meter to mine but given overall house consumption is around 1700kWh/a including solar contribution I doubt that it’s more than 1/3rd of that. Will get on that meter asap.


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
Gervase, I am changing the library but this will not chnge your assessment, so you have to do it manually
