### ISSUE TITLE
Allowance for 'set back' on thermostat settings

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#229]
Some people are now able to have 'set back' temperatures on their thermostats. (e.g. set to 15 degrees overnight). It would be nice to be able to accommodate this in the heating model - though not urgent.

**Comment by marianneURBED** [comment]
This has happened in another couple of assessments - so seems to be something that we'll have to accommodate to make the tool more usable. Changed from low to medium priority.

**Comment by cagabi** [comment]
I am having a look at the SAP brick and I don't think we can implement this issue without doing a dissertation or going for a very simplistic approach (which I think is good enough).

In the table 9c p.220 (one of my favourites) they explain the calculation of the heating requirement. For the purpose of this rant I'll simplify it (not taking into account weekends or rest of dwelling) and it is quite straight: 
- You know the temperature when heating is on (thermostat)
- You know how many hours the heating is off
- You know the external temperature
- You calculate the temperature reduction for each heating off period
- You calculate the mean temperature taking into account the temperature during heating (thermostat) and the reductions
- With that mean temperature you calculate the heat requirement.

Looking more into that Mean temperature:
```
T = Theating - reductions
```
In our case reductions are 0 so the mean temperature is the temperature during the heating period and here comes my simple assumption: would it be enough to just average between the 2 thermostat settings? 

ie. the settings are 21C for 17 hours and 15C for 7 hours then:
```
T = T1 x t1 / 24 + T2 x t2 /24 = 21*17/24 + 15*7/24 = 19.25C
T is temperature
t is amount of hours 
```
So the assessor could input in MHEP the set back thermostat temperature and the amount of hours per day.  

This would work if there is no heating off period. But I can imagine a typical case like this: 
- heating on 21C at 7am
- heating off at 9am
- heating on 21C 6pm
- heating on 15C at 11 pm

For something like that I don't know what we could do because the reduction of temperature depends completely on the thermostat setting when the heating goes off.

I think that the only viable option would be to have heating off periods or set back setting (for week days and weekends separately)
