### ISSUE TITLE
Ventilation shows as zero despite having two intermittent fans

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#231]
<img width="961" alt="screen shot 2017-01-18 at 14 23 08" src="https://cloud.githubusercontent.com/assets/16294193/22067571/c0d16fa4-dd89-11e6-843f-626f5adbaaee.png">

Is it maybe because they are too small to register?

**Comment by cagabi** [comment]
As this seemed to be a bug, I decided to check. I can say it is one of SAP incoherences.

For this you need to have a look at the SAP2012 worksheets,  calculation for 24d. You can see the value for 24d depends on the adjusted infiltration (22b), if it is higher than 1 we use one formula and if it isn't we use another one. In your case the adjusted infiltration (22b) is different  between scenarios: master has a chimney while in scenario 1 is capped. Because of this we apply the formula that make ventilatios loses to be 0.4 -> 0 W/K

I imagine it is not clear to understand just looking at the SAP worksheets, our calculations are the same than there but split in order to calculate ventilation separated for infiltrationn
