### ISSUE TITLE
Internal walls and floors

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#249]
Hi,
 MHEP's planner new friend Simon from Cardiff University is playing with the code and has come up with this point. Transcription of the conversation:

- S: With the thermal mass of the building it would be good if you can input the non-heat loss elements to the fabric list.
- C: Sorry my lack of knowledge which are those non-heat loss elements
- S: The non heat loss elements are internal walls and floors, these have thermal mass but don't loose heat to the outside.

I think the party walls could the job for the internal walls, but what about the floors?

**Comment by marianneURBED** [comment]
Hi, 

This is one of the places where we deviate from official SAP (and tend to use a generic TMP value). 

From experience we found that adding in the thermal mass of all the separate internal floors and walls made a very minimal difference to the results. It does however add a lot of time to data entry and potentially to data collection (depending on the complexity of the internal plan of the house) - and given the other sources of approximation, it's not really worth it (in our view). 

So we don't do this, but use a global value instead (tick-box at top of page) applied to all the heat loss elements (external floors, walls, roofs). 

I know this is a fudge, but one we felt was justified (whereas, for example, being more accurate in window measurements is worth it - probably because of the much bigger contribution of solar gain/ heat loss etc to heat demand). 

Arguably, we should add this as a feature - but for now it's probably not 'very high' priority.

**Comment by gervasemangwana** [comment]
Totally agree with Marianne on this. 

It's an incredible amount of extra work to get what will actually be quite approximate thermal mass values. 

I think we are happy with low middle and high. Definitely for the minute. 

G

**Comment by cagabi** [comment]
Uh I had forgot that TMP at all, thanks for the clarification.

**Comment by simonlannon** [comment]
Thanks for the replies this makes sense. The TMP genric value is fine.
Regards
Simon

**Comment by cagabi** [comment]
What shall I do with this? Can I close the issue?

**Comment by marianneURBED** [comment]
Yep, we're never going to do this. Let's close the issue.
