### ISSUE TITLE
When exporting/importing pictures don't transfer properly

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#257]
When I import data from one assessment to a new assessment, the pictures don't go with it in a way that can be seen (see image) - and then you can't delete the icons that are left in their place.  

![screen shot 2017-04-03 at 13 50 13 2](https://cloud.githubusercontent.com/assets/16305707/24610040/ffdf537a-1874-11e7-900c-287a90332218.png)

Setting as medium priority, as is possible to just upload the images again - but then you end up with multiple copies, and this could get v annoying over time (see image). 

![screen shot 2017-04-03 at 13 53 28 2](https://cloud.githubusercontent.com/assets/16305707/24610045/05c26c0a-1875-11e7-8976-7d5ef1b57e73.png)

**Comment by cagabi** [comment]
This is a very good point, the object in the code that holds all the data has the name of the files but not the files themselves, they are kept in a specific folder for each assessment. So the new assessment made from the import is looking for the files in its own folder and obviously not finding them

**Comment by cagabi** [comment]
More than fixing the bug, I have avoided it.

There is no reference to the original project in the exported data we only export the data to go throw the model. In order to import the images I'd have to do a bit of a mess. The final solution is that I completely empty the array that holds the names of the files which means emptying the gallery.
