### ISSUE TITLE
Only 20 images visible in Chrome and Firefox

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#266]
I can see all 40 images I uploaded in Safari.

**Comment by cagabi** [comment]
Strange I have been able to display 53 and decided to stop uploading pitures.

Which one is your assessment?

**Comment by cagabi** [comment]
Gervase, are you still having this issue, can I close it?

**Comment by gervasemangwana** [comment]
Just tried in firefox and yes, sort of

Uploaded 30 but it only did first 20. But then I’ve been able to upload the other 10 after. So not really a problem. Does that make sense?


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
How many can you see in Chrome?

**Comment by gervasemangwana** [comment]
In Chrome I can’t upload at all!!

When I click upload it closes the gallery page and goes back to main page. 

Can I make a request for a bulk delete image or delete all button. all this testing has led to me uploading the wrong things in the wrong places and individually deleting is looooooooong.

Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
Yes I know about the been able to upload in Chrome, it's so annoying! I was having a look at that yesterday as part of #282 and I have no idea what it can be :(

About bulk delete of pictures, it's the kind of feature that should be there. I've opened an issue for it (#301). Have you realized we are over 300 now!

And now back to my question, this issue is about you not been able to see all the pictures in the gallery when using Chrome. Is that still happening?

**Comment by cagabi** [comment]
This issue hasn't come up again so I close it

**Comment by marianneURBED** [comment]
Hi Carlos,

I think the reason this might not have come up is that we haven’t tried – could you re-open and assign to me to test it?

Thank you,

Marianne

**Comment by cagabi** [comment]
open again

**Comment by marianneURBED** [comment]
Superseded by new framework - hoping bugs don't repeat.
