### ISSUE TITLE
Repetition of items in Appendix A

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#269]
It's great that Windows and Walls don't repeat. I wonder about some other items too. 
8 Royston has 5 chimneys to be capped and filled and 3 intermittent extract vents to be added in one scenario. That's a lot of repeated text. Not sure how easy it is to implement that and where there may be other examples.

**Comment by marianneURBED** [comment]
I think this is something that happens on occasion - we've also had it with multiple chimney pillows - but as its usually 3-4 things rather than 20, I think we can live with it for now. Moving to lower priority.

**Comment by cagabi** [comment]
I have implemented the Apply Bulk Measure for the intentional vents and flues which will allow for example to cap more than one chimney.

I am going to do now the Extract Ventilation fans. According to @gervasemangwana what we want is to be able to add more than one at the same time. But do we also want to be able to apply the measure in bulk (the same measure to more than one of the already existing EVPs)?

**Comment by cagabi** [comment]
I have done add more than one EVP as a measure.
