### ISSUE TITLE
Create new scenario implications

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#277]
I am starting this new issue from what has come up in #267: the problem of the list measure not being copied over when creating a new scenario.

Now the the list is copied over as I understood this should be the way it works but after conversation with Jonathan (who talked with Marianne) it looks like not copying the list of measures can also be a good thing.

As far as I get there can be two different approaches when creating the scenarios:

- Each scenario is a unique whole retrofit: in this case it makes sense for each scenario to be copied from the master and apply all the relevant measures. But I can imagine situations when you may still want to create scenario from scenarios, for example scenario 1 has all the windows changed because the householders are 100% sure they want to do it. This scenario 1 becomes the _retrofit baseline_ and from it we create new scenarios which will be the ones the householder will look at when making a decision. In this case we want all the window measures to be copied over (and to take them into account when calculating cost for the scenarios and add them to the relevant table)

-  Incremental retrofit: When you are planning to do the retrofit in several stages and each new scenario represents a stage. In this case the measures applied in scenario 1 need to be in scenario 2 but we don't want them to be considered as measure. Doing it this way, we don't take them into account when calculating costs of the scenario or filling up the tables in  the report.

As a possible solution we can add a question to the pop up window when creating a new scenario saying something like "Should measures in original scenario still be treated as measure in the new scenario? Choosing yes means those measures will be taking into account when calculating totals costs for the scenario"

**Comment by marianneURBED** [comment]
Hi Carlos, 

I think this is as much about presentation as anything else - there is some sense in listing out all the measures applied in a particular scenario, but it risks becoming overwhelming, confusing and repetitive. 

The incremental retrofit as described in your second point is actually how most assessments we have ever done work. I can't actually think of a time when we've done each scenario as a unique whole house retrofit - because to get to the 2050 targets, there's actually a fairly limited range of things you can realistically do (insulate, insulate, insulate!). 

The vast majority of people we've come across are looking to tackle things in an incremental fashion. And even where they aren't - and they are planning to do a bigger lump of work in one go - they will most likely be rolling up things we suggest in scenario 1 and scenario 2, or scenario 2 and 3, in one package of work. 

Therefore, there is some logic to showing everything that has been applied in a particular scenario in the tables in the report - with all the costs etc. The difficulty in this is one of presentation. The amount of information gets a repetitive and overwhelming. It's also one of psychology - it risks making it all seem like a bigger job than it actually is, compared to it being presented in 'bite size' chunks. And because the information on measures in the tables is not presented in 'scenario order', it can be confusing to work out what's included in say Scenario 2 or 3, that wasn't already included - again clouding decision making and potentially creating feelings of overwhelm. 

I think the solution is something like this - for each scenario, show the information in the table in sections: 
Section 1: The things that are unique to that scenario. 
Section 2: The things that are included in this scenario from the previous scenario (assuming that we always work in numerical order), thereby affecting the calculations, but are not unique to this scenario. 
Section 3 (?): The things that are included in this scenario that were also included in the first scenario. 
The cost totals for each should be shown on each section of the table. See sketch: 
[EPSON031.PDF](https://github.com/emoncms/MyHomeEnergyPlanner/files/951414/EPSON031.PDF)
 
This potentially also helps cut-down on the repetition in the appendices - you don't need to list out the measures in the appendix that are already included in an earlier scenario - but we can look at this later. 

Thanks, 

Marianne

**Comment by cagabi** [comment]
Ok, It is clear to me how you want it.

I have put it back to how it was: now measures are not copied over when creating a new scenario.

I will do the rest soon.

**Comment by gervasemangwana** [comment]
Really? 

That does not work for me. I usually copy from scenario to scenario not from master. At least once in an assessment. I thought that was what marianne was saying too.

Maybe I misunderstand


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by marianneURBED** [comment]
Erm, yes think there's been a misunderstanding here. 

I do want measures to be copied from one scenario to another. So when I make scenario 2, I normally copy it from scenario 1, and assume that the measures in scenario 1 have been implemented, unless I over-ride one deliberately in scenario 2. 

So it's fine for the measures to be copied over - my point was that this could be confusing in the presentation, so I suggested a more refined way of showing this up in the report.

**Comment by marianneURBED** [comment]
Visualisation, which hopefully helps - scenario 2 usually builds on scenario 1, scenario 3 builds on scenario 2 etc. 
[Process diagram.pdf](https://github.com/emoncms/MyHomeEnergyPlanner/files/951599/Process.diagram.pdf)

**Comment by cagabi** [comment]
I want to do a clarification, in case it helps, about the meaning of copying measures over:

- If you make Scenario 2 as a copy of Scenario 1, the house in Scenario 2 is totally the same to Scenario 1: for example if you applied _SWEX_01 - 160-220mm External Wall Insulation on 225mm brick wall_ in scenario 1 then it will also be in scenario 2
- The question (for me) is if SWEX_01 is still considered a measure in scenario 2 or not. _Being considered a measure_ means that when calculating the cost for scenario 2, SWEX_01 will be taken into account, it also means that it will be added to the Measures tables in the report

**Comment by marianneURBED** [comment]
Right. That is clearer. 

Think that is fine for now - it is at least correct in the calcs. 

My suggestion to show the other 'measures applied' but not unique to that scenario in a different section of the tables in the reports can be implemented later, if we all agree it is the right thing to do. 

M

**Comment by marianneURBED** [comment]
Moving this to lower priority now. Think there is a debate to be had about how measures and associated costs are displayed in the report, but doesn't need to be sorted immediately.

**Comment by marianneURBED** [comment]
This is sorted now. Covered by a couple of lines of text in the report to clarify assumptions.
