### ISSUE TITLE
House picture arrows

### ISSUE THREAD

**Issue by ajnorthcott** [emoncms/MyHomeEnergyPlanner#288]
The house picture is great, but it is not always clear which label is associate with which arrow. Great if more more clarity possible?
Colour coding perhaps, or text nearer its arrow.
Andrew

**Comment by cagabi** [comment]
I remember moving the texts around in the past: the current positions respect to the arrows was the compromise when all the arrows are the same size (at a medium size that I don't remember). The problem is that with different arrow sizes it doesn't look that good. Then placing the text depending of the size of the arrow would be too complicated
So I have tried with color coding. First I tried with several colors but it doesn't work, it needs to be grey. So, because we cannot have alternate colors (even number of arrows) I have made the ones of the side lighter. To be honest I don't think it looks any clearer when an arrow is small as the text is still too far to the color.
What do you think?

**Comment by marianneURBED** [comment]
Think this is fine for now.
