### ISSUE TITLE
Text disappears from commentary box on householder questionnaire

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#311]
When typing into commentary box on householder questionnaire, if you move away from the page and come back, or refresh the page, the text disappears.

**Comment by cagabi** [comment]
Interesting enough this is something that has always happened. The problem was that the data only gets saved when you move away from one input (for example to another input) or when more than 5 seconds pass. So if you typed something and go to another page before those 5 secs, you loose it. 

I have half fixed this for the commentary: every 15 characters we save the data. I have done it this way because if we save it for every character changed then the program slows down. With this solution we may still loose the last 15 characters if you refresh the page too quickly but I couldn't think in a better compromise.

I'll keep this issue open just in case I think of a better solution.

**Comment by marianneURBED** [comment]
Closing #247 as this is the same issue.

**Comment by cagabi** [comment]
I am closing this now as the problem seems to be sorted
