### ISSUE TITLE
Nearly completed assessment now appears blank - HEA027 Garner

### ISSUE THREAD

**Issue by ajnorthcott** [emoncms/MyHomeEnergyPlanner#322]
Urgent request to recover data and rectify issues so that I can finish assessment and send report 
Impact this assessment - HEA027 Garner

Thanks

**Comment by cagabi** [comment]
Hi Andrew, it's fixed now.

The problem  was that you had ticked the "Use Solar Hot Water" but as that section was not properly filled the Qs (energy input from the solar system) was NaN (Not A Number), this not number was breaking the calculation of energy requirements for water heating.

I have changed the code so that the Qs becomes zero when it is NaN.

Beware that right now despite having the SHW checked it is like not having it as Qs is zero.
