### ISSUE TITLE
Update emonCMS framework

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#335]
To the most recent stable emonCMS branch

**Comment by TrystanLea** [comment]
Mostly updated in this branch:
https://github.com/emoncms/MyHomeEnergyPlanner/tree/emoncms9

There are still a couple of small issues around themeing & login screen

**Comment by TrystanLea** [comment]
I also wonder if we should move back to installing MyHomeEnergyPlanner as an emoncms module and perhaps document the modifications required that are specific to MyHomeEnergyPlanner?

i.e place assessment module in modules folder and then change user/login view to MHEP theme etc?

**Comment by TrystanLea** [comment]
Here's a screenshot of the mhep assessment module running in emoncms 9 with the blue navbar theme :)

![screenshot](https://user-images.githubusercontent.com/503186/36640434-6a15fa34-1a16-11e8-957c-64dbf6ea00a9.png)

**Comment by TrystanLea** [comment]
I've done a bit of work on the left hand menu, so that you can resize the page for a smaller screen and have it hide but then the option to show/hide it by clicking on the main menu item in the toolbar. This needs the latest version of emoncms master to work, its quite nice! :)

![mhep2](https://user-images.githubusercontent.com/503186/36670495-7f9d30cc-1af0-11e8-9fa7-35c185ca634d.png)

**Comment by TrystanLea** [comment]
I've now installed the MyHomeEnergyPlanner emoncms module on emoncms.org under Extras > MyHomeEnergyPlanner

**Comment by cagabi** [comment]
Trystan, great job! Thank you very much :)

**Comment by cagabi** [comment]
For those who move from the old version to this new one and want to keep their database you need to add a column to the users table: 
`ALTER TABLE users  ADD startingpage VARCHAR(64) DEFAULT 'assessment/list';`
