### ISSUE TITLE
'select from library' option in edit fabric item model?

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/MyHomeEnergyPlanner#342]
When building the original master scenario, If I make a mistake and need to change the wall type from say library element SWU_05 to SWU_01 I cant change this by clicking on edit. Instead I have to delete the element and recreate a new one. Is this an issue or by design?

**Comment by marianneURBED** [comment]
It's by design, though perhaps partly accidental - to do with the logic of the libraries and how measures are applied I think. 

It might be better, if possible, to be able to change the type without having to re-enter the dimensions in the master scenario, without it recording as a 'measure' - but that might require a bit of thinking time from Carlos, as I can see it might have knock-on effects elsewhere (when you change an element in scenarios, it gets recorded as a 'measure').

**Comment by cagabi** [comment]
Having a look when clicking on _edit_ doesn't give you many useful options more than changing the name.
I agre, I think it makes sense in the Master scenario to allow changing the type while in the scenarios keep the _apply measure_ as only way to do the changes

**Comment by TrystanLea** [comment]
> It might be better, if possible, to be able to change the type without having to re-enter the dimensions in the master scenario, without it recording as a 'measure'

Thanks @marianneURBED @cagabi. I've had a go at implementing this and I think I have it working in the way you suggest without affecting any of the measures code in the scenarios. I've implemented it in the module branch:

https://github.com/emoncms/MyHomeEnergyPlanner/commit/a56814f107349a687cf740509c8c515d09384feb

**Comment by cagabi** [comment]
Yeah, works as expected, thanks Trystan
