### ISSUE TITLE
Heat pump performance

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/MyHomeEnergyPlanner#360]
I notice that the default library that the three heat pumps included have particularly low efficiencies.

HPMP1:

   winter_efficiency: 230,
   summer_efficiency: 170,

HPMP2:

    winter_efficiency: 170,
    summer_efficiency: 170,

HPMP3:

    winter_efficiency: 170, 
    summer_efficiency: 170,

In the second energy savings trust study, the average performance for ground source was 2.8 and air-source 2.45. With a range of 1.6 to 3.8 for ground and 2.0 to 3.6 for air source.

http://www.energysavingtrust.org.uk/sites/default/files/reports/TheHeatisOnweb%281%29.pdf

I notice that a lot of the building fabric measures are caveated with installation quality notes eg:

_160-200mmmm thick vapour permeable external wall insulation system EWI with render finish. To include insulation to all window and door reveals and thresholds, treatment of roof eaves and verges junctions, taking insulation to at least 300mm below the level of the internal floor so thermal bridge is reduced. It will also require adjustments of external drainage pipework, and removal/refixing of sundry items satellite dishes, telephone connections, alarm boxes, boiler flues, bird boxes, gates and fences etc._  

I wonder if the same should apply to heat pump options. Where an option to select a well designed and installed heat pump could be an option?

**Comment by marianneURBED** [comment]
Hi Trystan,

Those are the default values from SAP – and in many cases won’t be far off the mark when you look at SPF, rather than the straight COP.

I have a job to do updating and separating the libraries properly – there will be a ‘Carbon Coop’ library, that contains the more detailed info, that we’re happy for our assessors to use and will be private to URBED/Carbon Coop/ CAfS (trained MHEP users); and a default library that will be a lot simpler, probably based on only publicly available data (e.g. from SAP) and will be fully editable by users.

I just haven’t had time to do this yet, but know it needs done, so it’s creeping up the priorities list.

Until it is, is there a way of using a blank/ old default library in the accessible OpenBEM library?

Thanks,

Marianne

**Comment by TrystanLea** [comment]
Thanks @marianneURBED 

> Until it is, is there a way of using a blank/ old default library in the accessible OpenBEM library?

Yes I think so, I will have a think about how that could be achieved.

**Comment by TrystanLea** [comment]
The performance values in the energy savings trust report are SPF figures:

    SPF H2: (Heat pump heat delivered) / (inlet fans + pumps + heat pump)
    SPF H4: (Heat pump heat delivered + immersion heat delivered) / (inlet fans + pumps + heat pump + immersion)

The SPF of 2.8 for ground and 2.45 for air source are SPF H4 and include any immersion heat input, pumps, auxiliary and input fans.

I noticed that the current library adds an additional 156 kWh for the central heating pump which should be included in the SPF figure above.

I wonder why there is such a difference with SAP defaults?

**Comment by marianneURBED** [comment]
See other comment - SAP is conservative in its assumptions. And also takes a while to get updated with new performance data. From my own experience of looking at installed systems that haven't been part of trials, the level of performance assumed in SAP is often really not that far off (and is sometimes much worse).

**Comment by TrystanLea** [comment]
Thanks @marianneURBED, amazing how much work has been done on MyHomeEnergyPlanner since the last time I tried it! Im trying to do an assessment for Claire and my new house, so getting up to speed with it again at the moment.

**Comment by marianneURBED** [comment]
Subsumed in general library updates.
