### ISSUE TITLE
Calculation of cost of walls measures

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#382]
Hi, this should be obvious but it is so obvious that I need to ask because I cannot believe it if it is wrong.

Not taking into account EWI, we are calculating the cost of a measure applied to a wall as _area x cost per sqm_

Shouldn't it be _netarea x cost per sqm_? Net area is the area minus window area.

It's would be such an obvious big error that I am wondering if there is a reason to do the calculation like this

**Comment by marianneURBED** [comment]
Hello, 
It is done that way on purpose - the idea being that the cost of the area where the windows are, which you're not covering with EWI, is roughly equivalent to the costs of the detailing around the windows - beads, trims, cills etc. So you'll be relived to know it's not a mistake and it can stay as it is. 

We also add area on this measure - that's because the surveys use the internal dimensions of the house, but EWI is applied to the external surface, and should also run past at floor junctions etc - so the total area will be bigger. 

Hope that's clear. 

M
