### ISSUE TITLE
Recommendations/ measures tables not loading in report

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#387]
Tables/ recommendations not loading in the report. 

Just shared assessment with Carlos - id253

**Comment by marianneURBED** [comment]
Scenarios names also not loading.

**Comment by cagabi** [comment]
I have fixed this. The problem was an error when applying measures to "Clothes drying facilities". The new drying facility was added to the list of facilities but was wrongly added to the list of measures. I have fixed the error in the code and also replaced the measure in the assessment so now it works and you don't need to do anything.

I don't think this error is related to #386
