### ISSUE TITLE
Hot water energy requirements are calculated incorrectly

### ISSUE THREAD

**Issue by idrysdale** [emoncms/MyHomeEnergyPlanner#428]
The heating loss due to a combination boiler is not getting calculated correctly within the model.

The value of this loss is calculated by the model, using a string stored on `system` called `combi_loss`, as shown here: https://github.com/carboncoop/openBEM/blob/master/openBEM.js#L1797

However, before storing`combi_loss`, emoncms strips `<` from it. This means `Storage combi boiler < 55 litres`, becomes `Storage combi boiler  55 litres` and subsequently doesn't satisfy the switch condition, and all loss gets recorded as 0.

This could be replicated by creating an assessment and selecting a heating system of CMBB4, 'Typical Gas/LPG Combi Boiler with radiators, with storage'. Then clicking 'Import Export', under 'Export', clicking 'Show Project Data', and search for `"combi_loss": "Storage combi boiler  55 litres"`.

**Comment by marianneURBED** [comment]
Hi Ian, 
This is one of the areas of the tool I'd like to simplify. This is because we often have limited information about the exact specification of existing heating systems, or indeed future ones that we're not specifying in detail - so at the moment possibly gives a slightly false degree of certainty anyway. Could tackle this bug as part of that. Losses will be fairly limited in any case here, so it won't be making a big overall difference to the end result.
