### ISSUE TITLE
Water Heating Demand

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#55]
In 5 Pev assessment

water heating demand in energy system is 49000kWh.

figures in water heating section don't seem to indicate this high demand

**Comment by cagabi** [comment]
Hi,

I have had a look at the not simple calculations of the water heating, very good as now i know well how they work. 

The reason for this high value for the water heating demand is that you inputted a wrong value for *Temperature factor from Table 2b*, instead of 65 it should be 0.65. This way the water heating demand goes down to 2495 kWh/year which is still high but sounds more reasonable. 

I have checked all the calculations in the model and they do exactly what the SAP2012 documents says, so i am quite confident the calculations are ok.

I'll close this issue now.

  Carlos

**Comment by gervasemangwana** [comment]
Thanks Carlos

Now I know something too.


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by gervasemangwana** [comment]
user error!


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk
