### ISSUE TITLE
When creating new element would be good if it defaulted to the element type you are in. e.g. floors

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#74]
Even when type is changed to floor for example

**Comment by gervasemangwana** [comment]
Even when creating new element would be good if it defaulted to the element type you are in. e.g. floors

**Comment by cagabi** [comment]
First bit of the issue is solved: now when you choose a different type the dropdowm of elements is updated.

I haven't immplemented the second part to go by default to the element type. It has shown to be quite messy to do so i'll focus on sommethinng more urgent and hopefuully come back to this.

  Carlos

**Comment by marianneURBED** [comment]
Done!
